{{ if .nuon.inputs.inputs.deploy_tailscale }}
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: "tailnet-proxies-{{.nuon.install.id}}"
spec:
  type: ingress
  replicas: 3
{{ else }}
---
{{ end }}
