[project]
name = "acme-sh-data-plane"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "kubernetes>=34.1.0",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
]
